from app.services.auth import email_delivery as _email_delivery
from app.services.auth import (
    PROXY_KEY_LIMIT,
    authenticate_user,
    begin_email_verification,
    build_auth_settings_response,
    confirm_email_verification,
    consume_password_reset_challenge,
    create_password_reset_challenge,
    create_proxy_api_key,
    create_session_for_auth_subject,
    delete_proxy_api_key,
    get_or_create_app_auth_settings,
    list_proxy_api_keys,
    require_password,
    revoke_all_refresh_tokens,
    revoke_refresh_token,
    revoke_refresh_token_family,
    rotate_proxy_api_key,
    rotate_refresh_token,
    send_email_verification_otp,
    send_password_reset_email,
    serialize_proxy_api_key,
    update_auth_settings,
    verify_proxy_api_key,
)

smtplib = _email_delivery.smtplib

__all__ = [
    "PROXY_KEY_LIMIT",
    "authenticate_user",
    "begin_email_verification",
    "build_auth_settings_response",
    "confirm_email_verification",
    "consume_password_reset_challenge",
    "create_password_reset_challenge",
    "create_proxy_api_key",
    "create_session_for_auth_subject",
    "delete_proxy_api_key",
    "get_or_create_app_auth_settings",
    "list_proxy_api_keys",
    "require_password",
    "revoke_all_refresh_tokens",
    "revoke_refresh_token",
    "revoke_refresh_token_family",
    "rotate_proxy_api_key",
    "rotate_refresh_token",
    "send_email_verification_otp",
    "send_password_reset_email",
    "smtplib",
    "serialize_proxy_api_key",
    "update_auth_settings",
    "verify_proxy_api_key",
]
